### PR TITLE
Mobile responsive bar charts

### LINKED ISSUE #379: Total sequences is cut off
The total number of sequences is cut off for large lineages. E.g. https://cov-spectrum.org/explore/World/AllSamples/Past6M/variants?pangoLineage=B.1.617.2*

We should allow Metric to take more width. (I'd like to continue showing the exact number of sequences.)

image

### LINKED ISSUE #405: Sequences over time bar chart not working
Since #403, the bar chart version of the sequences over time widget only shows a white space:

image

This can be reproduced in the preview version: https://cov-spectrum-develop-git-bug-overflow-fix-cov-spectrum.vercel.app/explore/Switzerland/AllSamples/Past6M/variants?pangoLineage=B.1.1.529*

I rolled back the public version.

(ping @gautier-collab)

### PR DESCRIPTION
**Pull request by gautier-collab**
_Branch created from `bug/overflow-fix` to which I manually re-implemented the code that had been reverted.
I copy-paste here the implementations mentioned on the abandonned pull request:_

Issue #405 and issue #379

Bar chart is displayed when the associated button is clicked.

Also fixed the bug of display of bar charts, happening when the viewport has a width between 650px and 1000px (so far not readable at all in the main branch) -> Fixed for all bar charts:
- Sequencing intensity (home page)
- Sequences over time
- Age demographics

Fixed the cut off of Total sequences over time

Metrics next to line charts and geographical distributions no longer cut off.

### CODE REVIEW

File: src/components/NamedCard.tsx [hunk 1]
```diff
@@ -71,7 +71,27 @@ export const TabbedCard = ({
                 : 'bg-gray-100 text-gray-500'
             }
           `}
-          onClick={_ => tabConfig.onNewTabSelect(index)}
+          onClick={_ => {
+            tabConfig.onNewTabSelect(index);
+
+            //let graphs = Array.from(
```
Comment (chaoran-chen) [inline src/components/NamedCard.tsx]: Please remove the commented-out code

File: src/widgets/common.tsx [hunk 2]
```diff
@@ -47,8 +47,17 @@ export const ChartAndMetricsWrapper = styled.div`
 `;
 
 export const ChartWrapper = styled.div`
-  flex-grow: 1;
-  width: 100%;
+  //flex-grow: 1;
```
Comment (chaoran-chen) [inline src/widgets/common.tsx]: Remove commented-out code

**Review by chaoran-chen — APPROVED** [review]
Perfect! Thanks.

Please just remove the unused code.
