### PR TITLE
Decouple the KnownVariantList from the Date Range Selector

### LINKED ISSUE #98: "Known variants" plots broken for 2020
When setting the time filter to 2020, the small plots on the "Known variants" buttons don't show any data ("0.0%"). I guess this is because we are filtering by 2020, but also by the last 3 or so months. Either we can make these plots work correctly (fetch the last 3 months of 2020), or just hide them properly (don't show "0.0%").

### PR DESCRIPTION
**Pull request by ningxie1991**
Fix for #98

1. Moved wholeSampleSet data loading from `ExploreFocusSplit` to the `KnownVariantList`
2. Set the dateRange to be `Past3M` across all API calls within `KnownVariantList` so it's not defined everywhere

image

image

### CODE REVIEW

File: src/components/KnownVariantsList/KnownVariantsList.tsx [hunk 1]
```diff
@@ -74,17 +80,31 @@ function selectPreviewVariants(
...
-  selection,
-  wholeSampleSetState,
-}: Props) => {
+/**
+ * For KnownVariantsList, we don't need very old data, since convertKnownVariantChartData (in load-data.ts)
+ * will only take the latest 2 months. However since our data collection lags by a couple
+ * of weeks, we need to fetch slightly more here to ensure we have enough. Therefore,
+ * we use past 3 months (Past3M) as the date range across all API calls within KnownVariantsList,
+ * e.g. useWholeSampleSet, getPangolinLineages, loadKnownVariantSampleSets.
+ * @param country
```
Comment (spacephoton) [inline src/components/KnownVariantsList/KnownVariantsList.tsx]: Don't think we need to add these in the comment, unless you use it with the IDE somehow? (But I think TS infers this stuff anyway)

**Review by spacephoton — APPROVED** [review]

File: src/components/KnownVariantsList/KnownVariantsList.tsx (hunk 1 above)
Comment (spacephoton) [reply src/components/KnownVariantsList/KnownVariantsList.tsx]: The @param stuff

Comment (ningxie1991) [reply src/components/KnownVariantsList/KnownVariantsList.tsx]: > The @param stuff

Ah they are auto generated when I added the JSDoc by typing `/** enter` . I can remove them.
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#param-and-returns
